### ISSUE TITLE
Location loading is a little glitchy switching from list to floorplan

### ISSUE THREAD

**Issue by gmarkv10** [gmarkv10/Shoptimize#32]
If we could be notified after the AsynchTask returns from getting all the valid locations that would be better than just waiting in a Handler for a set amount of time.  This makes activity switching slow, at least on an emulator and every now and then I get an odd NullPointerException.

**Comment by vtse0826** [comment]
The floorplan now waits until all locations are loaded from the database (no locations are loaded if the item is not in the database) before proceeding. No more NullPointerExceptions.
