### ISSUE TITLE
Crowdsourced points aren't guarenteed to be posted to the db

### ISSUE THREAD

**Issue by gmarkv10** [gmarkv10/Shoptimize#33]
There is a button in FloorPlanActivity to post the locations but Shoptimize doesn't trust its user base to click that reliably especially since there's no reception in most grocery stores.  A scripted locations poster that runs in the background after a store trip is complete would be best.

**Comment by vtse0826** [comment]
Locations are now posted to the database after a store trip is complete upon availability of internet access;
